### ISSUE TITLE
All plots: Make y-axis range configurable

### ISSUE THREAD

**Issue by JonasKellerer** [GenSpectrum/dashboard-components#264]
The maintainer should be able to set the max value of the y-axis.

Possible values are
- fixed value (default 100%)
- max in data
- min(max in data, 100%)

Develop a method to disable the logit scale option if the y-axis-max value is set to fixed value above 100% or max in data.

**Comment by corneliusroemer** [comment]
I'm not sure I understand `min(max in data, 100%)`? Probably both min and max value of y-axis should be configurable, not just max?

y-scale could benefit from different settings for logit and linear. The current settings seem to be mostly targeted at linear.

Default for logit could be something like:
- for min: max(0.0001, min_of_data)
- for max: min(0.9999, max_of_data)
Which means zooming in as much as possible but setting sensible cut-offs for 0/1 data

Right now logit scale is of limited use because the display range is too wide, squishing away the signal

<img width="754" alt="image" src="https://github.com/GenSpectrum/dashboards/assets/25161793/4fb7897d-1861-417d-84ca-9cae7dde0eb7">
