### ISSUE TITLE
Validate input of components

### ISSUE THREAD

**Issue by JonasKellerer** [GenSpectrum/dashboard-components#554]
Currently, we have no special validation for the inputs of our components. Derive a way to validate them. Do this first for one component.

In some places we have defaults (gs-prevalence-over-time, lapisDateField) for required fields, which can shadow a missing input. This should be fixed, so that required fields always need to be provided.

- [x] #557
- [x] #561
- [x] #568
- [x] #570
- [x] #571
- [x] #572
- [x] #563
- [x] #573
- [x] #574
- [x] #575
- [x] #576
- [x] #577
- [x] #578
- [x] #579
- [x] #599

**Comment by fengelniederhammer** [comment]
I investigated a little what happens when you pass invalid arguments to our components:
* When the type doesn't match (e.g. string instead of number, array instead of object), lit will inject `null` into the component class.
* When the structure of the type doesn't match (e.g. object with wrong keys), then there will be JS runtime errors, because technically lit still deserializes the object correctly, but our JS code gets unexpected objects.
